name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        if: startsWith(github.repository, 'StyleShit/')

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: 20.x

            - run: npm ci

            - name: Cache build
              id: cache-build
              uses: actions/cache@v4
              env:
                  cache-name: cache-build
              with:
                  path: ./dist
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            # See https://github.com/actions/checkout/blob/85e6279cec87321a52edac9c87bce653a07cf6c2/README.md#push-a-commit-using-the-built-in-token
            - name: Config git user
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Create release PR or publish
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: npm run release
                  commit: 'chore(release): publish'
                  title: 'chore(release): publish'
              env:
                  GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
