name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        if: startsWith(github.repository, 'StyleShit/')

        permissions:
            contents: write # to create release (changesets/action)
            issues: write # to post issue comments (changesets/action)
            pull-requests: write # to create pull request (changesets/action)

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: 20.x

            - run: npm ci

            - name: Config git user
              run: |
                  git config --global user.name "${{ secrets.CHANGESETS_ACTOR_NAME }}"
                  git config --global user.email "${{ secrets.CHANGESETS_ACTOR_EMAIL }}"

            - name: Create release PR or publish
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: npm run release
                  commit: 'chore(release): publish'
                  title: 'chore(release): publish'
                  setupGitUser: false
              env:
                  GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
